export const PREV_RUN_GAME_STATE = "PREV_RUN_GAME_STATE";
export const TIMEOUT_RUN_GAME = "TIMEOUT_RUN_GAME";
export const PREV_DND_GAME_STATE = "PREV_DND_GAME_STATE";
export const TIMEOUT_DND = "TIMEOUT_DND";
